/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package questionario;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcelo F Athayde
 */
public class Questionario extends javax.swing.JFrame {

    /**
     * Creates new form Questionario
     */
    public Questionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPergunta1 = new javax.swing.ButtonGroup();
        bgPergunta2 = new javax.swing.ButtonGroup();
        bgPergunta3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jrbHardware = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jrbBit = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jrb1000Megabyte = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jbSubmeter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("O termo técnico para designar a parte fisica do computador é: ");

        bgPergunta1.add(jRadioButton1);
        jRadioButton1.setText("Software");

        bgPergunta1.add(jrbHardware);
        jrbHardware.setText("Hardware");

        bgPergunta1.add(jRadioButton3);
        jRadioButton3.setText("Periféricos");

        bgPergunta1.add(jRadioButton4);
        jRadioButton4.setText("Modem");

        jLabel2.setText("A menor quantidade de edição binaria chama-se: ");

        bgPergunta2.add(jrbBit);
        jrbBit.setText("Bit");

        bgPergunta2.add(jRadioButton6);
        jRadioButton6.setText("Byte");

        bgPergunta2.add(jRadioButton7);
        jRadioButton7.setText("MicroByte");

        bgPergunta2.add(jRadioButton8);
        jRadioButton8.setText("MiniBite");

        jLabel3.setText("1 GigaByte corresponde aproximadamente a: ");

        bgPergunta3.add(jRadioButton9);
        jRadioButton9.setText("1000KB(quilobyte)");

        bgPergunta3.add(jRadioButton10);
        jRadioButton10.setText("10 bits");

        bgPergunta3.add(jrb1000Megabyte);
        jrb1000Megabyte.setText("1000 MB(Megabyte)");

        bgPergunta3.add(jRadioButton12);
        jRadioButton12.setText("10000 bytes");

        jbSubmeter.setText("Submeter");
        jbSubmeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSubmeterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbHardware)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton6)
                            .addComponent(jrbBit)
                            .addComponent(jRadioButton7)
                            .addComponent(jRadioButton8)
                            .addComponent(jRadioButton10)
                            .addComponent(jRadioButton9)
                            .addComponent(jRadioButton12)
                            .addComponent(jrb1000Megabyte)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jbSubmeter)
                        .addComponent(jLabel2)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbHardware)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbBit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton8)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrb1000Megabyte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jbSubmeter)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSubmeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSubmeterActionPerformed
        // TODO add your handling code here:
        if(!perguntaRespondida(bgPergunta1)){
            JOptionPane.showMessageDialog(null, "A pergunta 1 não foi respondida");
            return;
            
        }
          if(!perguntaRespondida(bgPergunta2)){
            JOptionPane.showMessageDialog(null, "A pergunta 1 não foi respondida");
            return;
             }
            if(!perguntaRespondida(bgPergunta3)){
            JOptionPane.showMessageDialog(null, "A pergunta 1 não foi respondida");
            return;
            }   
            int acertos =0 ;
            acertos+= jrbHardware.isSelected() ? 1 : 0;
            acertos+= jrb1000Megabyte.isSelected() ? 1 : 0;
            acertos+= jrbBit.isSelected() ? 1 : 0;
            JOptionPane.showMessageDialog(null, "Você acertou " +acertos + " resposta(s) ");
        
        
    }//GEN-LAST:event_jbSubmeterActionPerformed
private boolean perguntaRespondida(ButtonGroup pergunta){
    return pergunta.getSelection() !=null;
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Questionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgPergunta1;
    private javax.swing.ButtonGroup bgPergunta2;
    private javax.swing.ButtonGroup bgPergunta3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JButton jbSubmeter;
    private javax.swing.JRadioButton jrb1000Megabyte;
    private javax.swing.JRadioButton jrbBit;
    private javax.swing.JRadioButton jrbHardware;
    // End of variables declaration//GEN-END:variables
}
